# Render.com deployment configuration for Smart Doc Checker Backend

# Build command
buildCommand: |
  pip install --upgrade pip
  pip install -r requirements.txt
  cd backend
  mkdir -p uploads database logs

# Start command  
startCommand: cd backend && python -m uvicorn api.api_server:app --host 0.0.0.0 --port $PORT

# Environment variables
env:
  - key: PYTHON_VERSION
    value: "3.11.0"
  - key: PYTHONPATH
    value: "/opt/render/project/src/backend"
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: DATABASE_PATH
    value: "/opt/render/project/src/backend/database/smart_doc_checker.db"
  - key: UPLOAD_DIRECTORY
    value: "/opt/render/project/src/backend/uploads"

# Health check
healthCheckPath: /health

# Service type
serviceType: web

# Scaling
scaling:
  minInstances: 1
  maxInstances: 3
  
# Disk storage
disk:
  name: data
  mountPath: /opt/render/project/src/backend/database
  sizeGB: 1